---
# This is playbook-1
# In this playbook we will demonstrate the following
#   - Install a Package
#   - Configure a Service to Start at Boot

- name: Install the Apache HTTPD Server
  yum: name=httpd state=present

- name: Configure HTTPD to Start at Boot
  service:
    name: httpd
    enabled: yes
    state: started
