### Playbook 3

- name: Playbook Three - Templates and Files
  hosts: all
  roles:
    - role: common
    - role: web
      when: ansible_facts['os_family'] == 'RedHat'
    - role: db
      when: ansible_facts['os_family'] == 'Ubuntu'
  become: true
