---
# Show Ansible Facts
# Display the Hostname

# https://docs.ansible.com/ansible/latest/modules/hostname_module.html
- name: Change the Hostname
  hostname: name="{{ machine_host_name }}"

## Add the Web Server to /etc/hosts
- name: Add obtools to the /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '192.168.33.10	web'
  become: true

## Add the DB Server to /etc/hosts
- name: Add obtools to the /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '192.168.33.20	db'
  become: true
